copy repo

diff --git a/usb b/usb
--- a/usb
+++ b/usb
@@ -17,20 +17,20 @@ die() {
   exit 1
 }
 
-if [ ! -d rootfs ]; then
-  die "directory 'rootfs': not found"
-fi
-
-if [ ! -x server ]; then
-  die "script 'server': not found"
+if ! grep -q binfmt_misc /proc/mounts; then
+  die "unsupported hardware"
 fi
 
 if [ ! -b "$USB" ]; then
   die "usb drive '$USB': not found"
 fi
 
-if ! grep -q binfmt_misc /proc/mounts; then
-  die "unsupported hardware"
+if [ ! -d rootfs ]; then
+  die "directory 'rootfs': not found"
+fi
+
+if [ ! -x server ]; then
+  die "script 'server': not found"
 fi
 
 if [ -e /tmp/server ]; then
@@ -126,14 +126,13 @@ printf "nameserver %s\n" "$ROUTE" > /tmp/server/etc/resolv.conf
   printf "PARTUUID=%s /boot vfat ro,noatime 0 2\n" "$BOOTFS"
 } >> /tmp/server/etc/fstab
 
-sed -i "s#root=/dev/mmcblk0p2#root=PARTUUID=$ROOTFS ro forcefsck net.ifnames=0#g" /tmp/server/boot/cmdline.txt
+sed -i "s|root=/dev/mmcblk0p2|root=PARTUUID=$ROOTFS net.ifnames=0|g" /tmp/server/boot/cmdline.txt
 
 printf "disable_splash=1\n" >> /tmp/server/boot/config.txt
 
 # copy
 
-rsync -aAX rootfs /tmp/server/root/ # server files
-rsync -aAX server /tmp/server/root/ # install script
+rsync -aAX ./ /tmp/server/root/
 
 chown -R root:root /tmp/server/root
 
