rewrite wg-gen

diff --git a/tools/wg-gen b/tools/wg-gen
--- a/tools/wg-gen
+++ b/tools/wg-gen
@@ -2,154 +2,143 @@
 
 set -e
 
-# default
+OUTPUT="./wireguard"
+HOST_PORT=51820
 
-PEER_TOTAL=1
-PORT=51820
-RANGE=
+gen_pre() {
+  num1=$(openssl rand -hex 1)
+  num2=$(openssl rand -hex 2)
+  num3=$(openssl rand -hex 2)
+  num4=$(openssl rand -hex 2)
 
-check() {
-  if [ -z "$ENDPOINT" ]; then
-    die "endpoint required"
-  fi
-
-  if [ -z "$PORT" ]; then
-    die "port required"
-  fi
-
-  if [ -z "$PEER_TOTAL" ]; then
-    die "peer total required"
-  fi
-
-  # TO-DO - increase limit
-  if [ "$PEER_TOTAL" -ge 65535 ]; then
-    die "peer total cannot exceed 65535" # ffff
-  fi
-
-  if ! command -v wg > /dev/null; then
-    die "wireguard-tools not installed"
-  fi
-
-  if ! command -v qrencode > /dev/null; then
-    die "qrencode not installed"
-  fi
-
-  if [ -e wireguard ]; then
-    die "directory 'wireguard': already exists"
-  fi
+  # printf 'fd%02x:%04x:%04x:%04x\n' "$num1" "$num2" "$num3" "$num4"
+  printf 'fd%s:%s:%s:%s\n' "$num1" "$num2" "$num3" "$num4"
 }
 
-gen_subnet() {
-  num1=$(openssl rand -hex 1) # 0-255
-  num2=$(openssl rand -hex 2) # 0-65535
-  num3=$(openssl rand -hex 2) # 0-65535
-  num4=$(openssl rand -hex 2) # 0-65535
+gen_ip() {
+  int="$1"
+  peer="$2"
 
-  # printf 'fd%02x:%04x:%04x:%04x::\n' "$num1" "$num2" "$num3" "$num4"
-  printf 'fd%s:%s:%s:%s::\n' "$num1" "$num2" "$num3" "$num4"
+  printf '%s::%x\n' "$WG_PREFIX" "$int"
+  printf 'local-data: "%s AAAA %s::%x"\n' "$peer" "$WG_PREFIX" "$int" >> .unbound.conf
 }
 
-gen_addr() {
-  printf '%s%x\n' "$SUBNET" "$1"
+gen_wg() {
+  HOST_ADDR=$(gen_ip 1 server)
 
-  printf 'local-data: "%s AAAA %s%x"\n' "$1" "$SUBNET" "$1" >> unbound.conf
-}
-
-gen_peers() {
-  install -d -m 700 wireguard
-  cd wireguard
-
-  SERVER_KEY=$(wg genkey)
-  SERVER_PUB=$(printf %s "$SERVER_KEY" | wg pubkey)
-
-  SERVER_ADDR=$(gen_addr 1)
+  HOST_KEY=$(wg genkey)
+  HOST_PUB=$(printf %s "$HOST_KEY" | wg pubkey)
 
   {
-    printf "%s\n" "[Interface]"
-    printf "%s\n" "PrivateKey = ${SERVER_KEY}"
-    printf "%s\n" "Address = ${SERVER_ADDR}/64"
-    printf "%s\n" "ListenPort = ${PORT}"
+    out "[Interface]"
+    out "PrivateKey = ${HOST_KEY}"
+    out "Address = ${HOST_ADDR}/64"
+    out "ListenPort = ${HOST_PORT}"
   } > 1-server.conf
 
-  for peer in $(seq "$1"); do
-    peer=$((peer + 1))
+  int=1
+  for peer in "$@"; do
+    int=$((int + 1))
+    name="${int}-${peer}"
+
+    PEER_ADDR=$(gen_ip "$int" "$peer")
+
+    PSK=$(wg genpsk)
 
     PEER_KEY=$(wg genkey)
     PEER_PUB=$(printf %s "$PEER_KEY" | wg pubkey)
 
-    PSK=$(wg genpsk)
-
-    PEER_ADDR=$(gen_addr "$peer")
-
     {
-      printf "\n"
-      printf "%s\n" "[Peer]"
-      printf "%s\n" "PublicKey = ${PEER_PUB}"
-      printf "%s\n" "PresharedKey = ${PSK}"
-      printf "%s\n" "AllowedIPs = ${PEER_ADDR}/128"
+      out
+
+      out "[Peer]"
+      out "PublicKey = ${PEER_PUB}"
+      out "PresharedKey = ${PSK}"
+      out "AllowedIPs = ${PEER_ADDR}/128"
     } >> 1-server.conf
 
     {
-      printf "%s\n" "[Interface]"
-      printf "%s\n" "PrivateKey = ${PEER_KEY}"
-      printf "%s\n" "Address = ${PEER_ADDR}/128"
-      printf "%s\n" "DNS = ${SERVER_ADDR}"
+      out "[Interface]"
+      out "PrivateKey = ${PEER_KEY}"
+      out "Address = ${PEER_ADDR}/128"
+      out "DNS = ${HOST_ADDR}"
 
-      printf "\n"
+      out
 
-      printf "%s\n" "[Peer]"
-      printf "%s\n" "PublicKey = ${SERVER_PUB}"
-      printf "%s\n" "PresharedKey = ${PSK}"
-      if [ -n "$RANGE" ]; then
-        printf "%s\n" "AllowedIPs = ${SUBNET}/64"
-      else
-        printf "%s\n" "AllowedIPs = ${SERVER_ADDR}/128"
-      fi
-      printf "%s\n" "Endpoint = ${ENDPOINT}"
-    } > "$peer".conf
+      out "[Peer]"
+      out "PublicKey = ${HOST_PUB}"
+      out "PresharedKey = ${PSK}"
+      out "AllowedIPs = ${WG_PREFIX}::/64"
+      out "Endpoint = ${WG_ENDPOINT}"
+    } > "${name}.conf"
 
-    qrencode -r "$peer".conf -o "$peer".png
+    qrencode -r "${name}.conf" -o "${name}.png"
   done
 }
 
-usage() {
-  RST='\033[0;00m'
-  GRN='\033[0;32m'
-  YLW='\033[0;33m'
+pkg() {
+  cmd=$(command -v "$1")
+  [ -x "$cmd" ]
+}
 
-  printf "%b\n" "${YLW}USAGE${RST}:"
-  printf "%s\n" "    wg-gen [OPTIONS] <endpoint>:<port>"
-  printf "\n"
-  printf "%b\n" "${YLW}OPTIONS${RST}:"
-  printf "%b\n" "    ${GRN}-t <peer_total>${RST}    Total number of peers to generate (default: 1)"
-  printf "%b\n" "    ${GRN}-p <port>${RST}          Listening port (default: 51820)"
-  printf "%b\n" "    ${GRN}-r${RST}                 Allow access to entire subnet"
-
-  exit 0
+out() {
+  printf "%s\n" "$*"
 }
 
 die() {
-  printf "wg-gen: %s\n" "$*" >&2
+  printf "%s: %s\n" "${0##*/}" "$*" >&2
   exit 1
 }
 
-# TO-DO - add ipv4 '-4' option
-while getopts :t:e:p:hru opt; do
+while getopts o:e:p:P:g opt; do
   case $opt in
-    h) usage ;;
-    t) PEER_TOTAL="$OPTARG" ;;
-    p) PORT="$OPTARG" ;;
-    r) RANGE=1 ;;
-    *) die "unknown option" ;;
+    o)
+      OUTPUT="$OPTARG"
+      ;;
+    e)
+      WG_ENDPOINT="$OPTARG"
+      ;;
+    p)
+      HOST_PORT="$OPTARG"
+      ;;
+    P)
+      WG_PREFIX="$OPTARG"
+      ;;
+    g)
+      gen_pre
+      exit
+      ;;
+    *)
+      die "unknown option"
+      ;;
   esac
 done
-
 shift $((OPTIND - 1))
 
-ENDPOINT="$1"
+if ! pkg wg; then
+  die "wireguard-tools not installed"
+fi
 
-check
+if ! pkg qrencode; then
+  die "qrencode not installed"
+fi
 
-SUBNET=$(gen_subnet)
+if [ $# -eq 0 ]; then
+  die "peer name(s) required"
+fi
 
-gen_peers "$PEER_TOTAL"
+if [ -z "$WG_ENDPOINT" ]; then
+  die "endpoint required"
+fi
+
+if [ -z "$WG_PREFIX" ]; then
+  WG_PREFIX=$(gen_pre)
+fi
+
+mkdir -m 700 "$OUTPUT"
+cd -- "$OUTPUT"
+
+gen_wg "$@"
+
+column -t -o " " .unbound.conf > unbound.conf
+rm .unbound.conf
